version: '3.8'

services:
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - '5432:5432'

  adonis:
    image: node:22.12-alpine
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3333:3333'
    env_file:
      - .env
    command: >
      sh -c "npm install && node ace serve --watch"
    depends_on:
      - postgres

volumes:
  postgres_data:
